### ISSUE TITLE
Remove `deleted` from results.

### ISSUE THREAD

**Issue by TheMisir** [griffinpp/objection-soft-delete#12]
It may be done using changing `Model.$formatJson`. I can do it manually but wish to use with that library.

**Comment by griffinpp** [comment]
@TheMisir my first thought is that even if this is something that could be done with an option (doing it by default would just mean that someone who _doesn't_ want it that way has to set an option), it's something you'd be setting on a per-model basis, or else you'd have to set up a base model for everything else to inherit from.  In either case, `.$formatJson` would work just as well and not really represent any more work than anything that could be written into this library.

**Comment by TheMisir** [comment]
Yes, you're right
