### ISSUE TITLE
Model callbacks

### ISSUE THREAD

**Issue by JoaoCnh** [griffinpp/objection-soft-delete#5]
When I use this plugin in a Model what does **afterDelete** do?

Does it run after soft-delete or hard-delete?

Is there any **afterHardDelete**?

**Comment by griffinpp** [comment]
right now, `afterDelete` will only run after `.hardDelete` is called, which is probably not what what is expected.  I'll have to put out an update with something that makes more sense.

**Comment by JoaoCnh** [comment]
@griffinpp Right now it actually fits my requirement. But yes totally agree that there should be 2 different callbacks

**Comment by griffinpp** [comment]
@JoaoCnh I've been chatting w objection's primary dev, and it looks like the best that could be done with the public api is to have `$afterDelete` run after both `.delete()`, and `.hardDelete()`.  I would have liked to have separate callbacks for both, but it doesn't look like custom life cycle functions are possible right now. I think having it run after both will still make more sense than what is happening now, so I will work on that this evening and should have something out as soon as I can get it properly tested.  

Thanks for bringing this up!

**Comment by trenunu** [comment]
@griffinpp Thanks for ur job on this plugin.

Can you please give me some simple code example on how would you trigger $afterDelete after delete() and hardDelete()?

Many thanks

**Comment by griffinpp** [comment]
@trenunu sorry for the late response.  I will be updating the plugin shortly with what I hope will be a simple solution to this issue.

**Comment by griffinpp** [comment]
I have just published an update that adds some flags to the `queryContext` that is passed to the lifecycle functions.  See: https://github.com/griffinpp/objection-soft-delete#lifecycle-functions.  After trying a few crazier things, this seemed like the cleanest, sanest way to handle this particular issue.

**Comment by griffinpp** [comment]
Closing this issue.
